### ISSUE TITLE
Arcadia DNS Tool 

### ISSUE THREAD

**Issue by fletchnj** [f5devcentral/xcmcndemoguide#9]
I am having trouble with the [Arcadia DNS Tool](https://tool.xc-mcn.securelab.online). After following the demo guide and attempting to send the CNAME and ACME_CHALLENGE records, I received an error message at the bottom of the page that reads "Request failed with status code 401".

**Comment by yoctoalex** [comment]
Thank you for the feedback. The issue has been resolved.
